# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  
  database:
    image: "postgres:latest"
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ../database/start_up/:/docker-entrypoint-initdb.d/
      - ../database/volume:/var/lib/postgresql/data
      - ../database/downloads:/downloads
      
    env_file:
      - path: ./.env
        required: true

  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3005:3005

